### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by RamanGouda** [sunfounder/SunFounder_PiCar#2]
while Following Manual installation from doc PiCar-s_User_Manual.pdf , i ran
ptyhon setup.py install command 
and i got the following error

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by sunfounder** [comment]
Hi
Thanks for contacting us.

This is a module without setuptools, indicating that python lacks this module. You can try the following:
Wget HTTP: / / http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
The tar - XVF setuptools 0.6 c11. Tar. Gz
CD setuptools 0.6 c11
Python setup. Py build
Python setup. Py install
Then install and try the ptyhon setup.py install command



Best Regards
Jake 

support@sunfounder.com
 
From: RamanGouda
Date: 2018-07-11 06:55
To: sunfounder/SunFounder_PiCar
CC: Subscribed
Subject: [sunfounder/SunFounder_PiCar] ImportError: No module named setuptools (#2)
while Following Manual installation from doc PiCar-s_User_Manual.pdf , i ran
ptyhon setup.py install command
and i got the following error
Traceback (most recent call last):
File "setup.py", line 9, in 
from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by RamanGouda** [comment]
after trying
wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
i am getting the following error
--2018-07-12 13:45:59--  http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
Resolving pypi.python.org (pypi.python.org)... 151.101.20.223, 2a04:4e42:5::223
Connecting to pypi.python.org (pypi.python.org)|151.101.20.223|:80... connected.
HTTP request sent, awaiting response... 403 SSL is required
2018-07-12 13:45:59 ERROR 403: SSL is required.

**Comment by xtrimsystems** [comment]
Hi @RamanGouda "403 SSL is required" means that needs to be a secure connection. 
Use https instead: 
```wget https://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz```

**Comment by kellycampbe** [comment]
I ran into this same issue when setting up my picar-s tonight. After reading this issue, I ran 

> wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python

 which downloaded and installed setup tools all at the same time, and got me past this issue.  I found that command on the [setuptools pip project site](https://pypi.org/project/setuptools/3.8.1).
