### ISSUE TITLE
picar command IOError

### ISSUE THREAD

**Issue by hlaredo** [sunfounder/SunFounder_PiCar#5]
I am having a problem when running picar command ...

pi@PiCarS ~ $ picar
Traceback (most recent call last):
  File "/usr/local/bin/picar", line 8, in <module>
    load_entry_point('SunFounder-PiCar==1.0.1', 'console_scripts', 'picar')()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 43, in main
    setup()
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/__init__.py", line 80, in setup
    pwm=PCA9685.PWM(bus_number=1)
  File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/SunFounder_PCA9685/PCA9685.py", line 116, in __init__
    self.bus = smbus.SMBus(self.bus_number)
IOError: [Errno 2] No such file or directory

**Comment by sunfounder** [comment]
Hi dear,
Thank you for your support on us,could you give us your order number and the order screenshot,so that our after-sale can help you deal with it.Thanks.

Regards,
Sunfounder team


support@sunfounder.com
 
From: hlaredo
Date: 2018-11-11 12:30
To: sunfounder/SunFounder_PiCar
CC: Subscribed
Subject: [sunfounder/SunFounder_PiCar] picar command IOError (#5)
pi@PiCarS ~ $ picar
Traceback (most recent call last):
File "/usr/local/bin/picar", line 8, in 
load_entry_point('SunFounder-PiCar==1.0.1', 'console_scripts', 'picar')()
File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/init.py", line 43, in main
setup()
File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/init.py", line 80, in setup
pwm=PCA9685.PWM(bus_number=1)
File "/usr/local/lib/python2.7/dist-packages/SunFounder_PiCar-1.0.1-py2.7.egg/picar/SunFounder_PCA9685/PCA9685.py", line 116, in init
self.bus = smbus.SMBus(self.bus_number)
IOError: [Errno 2] No such file or directory

**Comment by hlaredo** [comment]
Hi,

I purchased this PiCar-S on Amazon. Attached is the order and details.


Let me know what are the next steps.

Thanks,

Horacio

**Comment by sunfounder** [comment]
Hi dear,
Please try to check the wiring on the expansion board and reinsert it.



support@sunfounder.com
 
From: hlaredo
Date: 2018-11-12 13:27
To: sunfounder/SunFounder_PiCar
CC: SunFounder; Comment
Subject: Re: [sunfounder/SunFounder_PiCar] picar command IOError (#5)
Hi,

I purchased this PiCar-S on Amazon. Attached is the order and details.


Let me know what are the next steps.

Thanks,

Horacio

**Comment by DonGiovanni83** [comment]
I am getting the same error. Car is wired  up correctly.

**Comment by kellycampbe** [comment]
I ran into this same error when setting my picar-s up tonight. After looking through the php files, I discovered that I needed to enable IC2.  I ran `sudo raspi-config` and chose to enable IC2 and then the picar command works.
