### ISSUE TITLE
ImportError: No module named picar

### ISSUE THREAD

**Issue by iamfel** [sunfounder/SunFounder_PiCar#6]
I ran this code " python line_follower.py "
and it showed no module named picar.

Traceback (most recent call last):
  File "line_follower.py", line 15, in <module>
    from picar import front_wheels
ImportError: No module named picar

**Comment by sunfounder** [comment]
Hi dear,
Could we know which version of the picar are you using?
please send us a code error screenshot ,it will be helpful for us to solve the issue for you.
Thanks in advance.



Best Regards,
SunFounder Team
 
From: iamfel
Date: 2019-05-09 22:16
To: sunfounder/SunFounder_PiCar
CC: Subscribed
Subject: [sunfounder/SunFounder_PiCar] ImportError: No module named picar (#6)
I ran this code " python line_follower.py "
and it showed no module named picar.
Traceback (most recent call last):
File "line_follower.py", line 15, in 
from picar import front_wheels
ImportError: No module named picar

**Comment by iamfel** [comment]
I will send the required information.
